# ===========================
# SERVER CONFIG
# ===========================
server.port=8080

# ===========================
# DATABASE CONFIG
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker_db
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA / HIBERNATE CONFIG
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===========================
# APP NAME
# ===========================
spring.application.name=job-tracker


# ===========================
# JWT CONFIG
# ===========================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000